---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      annotations:
#        sidecar.istio.io/inject: 'false'
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: belenot/website:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  website
spec:
  prefix: "/"
  host: belenot.com
  service: http://website.default